
image: macOS

environment:
    APPVEYOR_CONSOLE_DISABLE_PTY: true

install:
  - curl -o python.pkg https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - sudo installer -pkg python.pkg -target /
  - python3 -m pip install -r requirements.txt
  - curl -L -o electron.zip https://github.com/electron/electron/releases/download/v6.1.7/electron-v6.1.7-darwin-x64.zip
  - unzip electron.zip
  - rm electron.zip
  - curl -o R.framework.tar.bz2 https://www.jamovi.org/misc/R.framework.tar.bz2
  - curl -o base.tar.bz2        https://www.jamovi.org/misc/base.tar.bz2
  - tar xf R.framework.tar.bz2
  - tar xf base.tar.bz2
  
  # nanomsg
  - curl -L -o nanomsg.tar.gz https://github.com/nanomsg/nanomsg/archive/1.1.5.tar.gz
  - mkdir -p nanomsg
  - tar xf nanomsg.tar.gz --strip-components=1 -C nanomsg
  - cd nanomsg
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target install
  - cd ..
  - cd ..
  
  # boost
  - curl -L -o boost.tar.bz2 https://netix.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2
  - mkdir -p boost
  - tar xf boost.tar.bz2 --strip-components=1 -C boost
  - cd boost
  - ./b2 -j4 install
  - cd ..
  
  # protocol buffers
  - curl -L -o pb.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-cpp-3.11.4.tar.gz
  - mkdir -p pb
  - tar xf pb.tar.gz --strip-components=1 -C pb
  - cd pb
  - ./configure
  - make
  - make install
  - cd ..

build_script:
  - python3 setup.py py2app --includes _nanomsg_ctypes,_nanomsg_cpy,chardet,ezodf,openpyxl
  - mv dist/jamovi.app .
  - cp *.dylib jamovi.app/Contents/Frameworks
  - cp Info.plist jamovi.app/Contents
  - cp    Electron.app/Contents/MacOS/Electron   jamovi.app/Contents/MacOS/jamovi
  - cp -r Electron.app/Contents/Frameworks/*     jamovi.app/Contents/Frameworks
  - cp    Electron.app/Contents/Resources/electron.asar   jamovi.app/Contents/Resources
  - mkdir -p jamovi.app/Contents/Resources/modules
  - cp R.framework/Versions/3.6/Resources/bin/exec/R  jamovi.app/Contents/MacOS
  - mv R.framework jamovi.app/Contents/Frameworks
  - mv base  jamovi.app/Contents/Resources/modules
  - git clone --single-branch --branch current-dev --recurse-submodules -j8 https://github.com/jamovi/jamovi.git jamovi.app/Contents/Resources/jamovi
  - cp env.conf     jamovi.app/Contents/Resources
  - cp package.json jamovi.app/Contents/Resources
  - mkdir -p jamovi.app/Contents/build
  - mkdir -p jamovi.app/Contents/Resources/include
  - mv boost jamovi.app/Contents/Resources/include
  - cd jamovi.app/Contents/Resources
  - npm install -g asar
  - npm install jamovi/jamovi-compiler
  - cd jamovi/engine
  - ./configure
  - cd ../..
  
  - npm run build:all
  
  - cd ../../..
  - pwd
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip

artifacts:
  - path: jamovi.zip
    name: app-bundle
