
image: macOS

install:
  - curl -o python.pkg https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - sudo installer -pkg python.pkg -target /
  - python3 -m pip install -r requirements.txt
  - curl -L -o electron.zip https://github.com/electron/electron/releases/download/v6.1.7/electron-v6.1.7-darwin-x64.zip
  - unzip electron.zip
  - rm electron.zip
  - curl -o R.framework.tar.bz2 https://www.jamovi.org/misc/R.framework.tar.bz2
  - curl -o base.tar.bz2        https://www.jamovi.org/misc/base.tar.bz2
  - tar xf R.framework.tar.bz2
  - tar xf base.tar.bz2

build_script:
  - python3 setup.py py2app --includes _nanomsg_ctypes,_nanomsg_cpy,chardet,ezodf,openpyxl
  - mv dist/jamovi.app .
  - cp *.dylib jamovi.app/Contents/Frameworks
  - cp Info.plist jamovi.app/Contents
  - cp    Electron.app/Contents/MacOS/Electron   jamovi.app/Contents/MacOS/jamovi
  - cp -r Electron.app/Contents/Frameworks/*     jamovi.app/Contents/Frameworks
  - cp    Electron.app/Contents/Resources/electron.asar   jamovi.app/Contents/Resources
  - mkdir -p jamovi.app/Contents/Resources/modules
  - mv R.framework jamovi.app/Contents/Frameworks
  - mv base  jamovi.app/Contents/Resources/modules
  - git clone --single-branch --branch current-dev --recurse-submodules -j8 https://github.com/jamovi/jamovi.git jamovi.app/Contents/Resources/jamovi
  - cp package.json jamovi.app/Contents/Resources
  - cd jamovi.app/Contents/Resources
  - npm install jamovi/jamovi-compiler
  - npm run build:electron
  - npm run build:analyses
  - cd ../..
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip

artifacts:
  - path: jamovi.zip
    name: app-bundle
