
image: macOS

install:
  - curl -o python.pkg https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - sudo installer -pkg python.pkg -target /
  - python3 -m pip install -r requirements.txt
  - curl -L -o electron.zip https://github.com/electron/electron/releases/download/v6.1.7/electron-v6.1.7-darwin-x64.zip
  - unzip electron.zip
  - rm electron.zip

build_script:
  - python3 setup.py py2app --includes _nanomsg_ctypes,_nanomsg_cpy,chardet,ezodf,openpyxl
  - mv dist/jamovi.app .
  - cp *.dylib jamovi.app/Contents/Frameworks
  - ditto -c -k --sequesterRsrc --keepParent jamovi.app jamovi.zip

artifacts:
  - path: '*.zip'
    name: app-bundle
