
image: macOS

install:
  - curl -o python.pkg https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
  - sudo installer -pkg python.pkg -target /

build_script:
  - python3 setup.py py2app
  - ls
